name: pixsense
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #  transformers: ^0.1.0
  #  flutter_tts: ^3.3.0
  firebase_auth: ^5.4.0
  camera: ^0.10.5+5
  firebase_core: ^3.10.0
  cached_network_image: ^3.2.1
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.8
  #  convex_bottom_bar: ^3.2.0
  carousel_slider: ^5.0.0
  card_swiper: ^3.0.1
  #  tflite: ^1.1.2
  google_ml_kit: ^0.19.0
  google_mlkit_translation: ^0.12.0
  #  image: ^3.0.8
  #  image_picker: ^1.1.2
  file_picker: ^5.0.0
  tflite_flutter: ^0.10.1
  convex_bottom_bar: ^3.0.0
  image_picker: ^0.8.4+4
  tflite: ^1.1.2
  image: ^3.0.8
  http: ^0.13.3
  json: ^0.20.4
  flutter_spinkit: any
  path_provider: ^2.0.15
  google_translator: any
  flutter_tts: ^3.6.3  # For text-to-speech functionality
  translator: ^0.1.7   # For translation functionality
  flutter_cache_manager: ^3.3.1  # Better cache management
  connectivity_plus: ^5.0.1  # Check internet connectivity
  retry: ^3.1.2  # Helpful for API retries
  permission_handler: ^11.3.1
  lottie: any
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.1.1
  flutter_staggered_animations: ^1.1.1
  video_player: ^2.7.0
  chewie: any
  ffmpeg_kit_flutter: ^5.1.0
  universal_html: ^2.0.8
  speech_to_text: ^6.1.1
  animate_do: ^3.1.2
  glassmorphism: ^3.0.0
  shimmer: ^2.0.0
  google_fonts: any
  flutter_svg: ^2.0.5
  cloud_firestore: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    #    - blip_image_captioning_large.tflite
    - assets/images/
    - assets/images/background1.jpg
    - assets/images/background2.jpg
    - assets/images/background3.jpg
    #    - assets/images/PiXsense.png
    - assets/images/PiXsense1.png
    - assets/images/PiXsensebg.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
